[build]
builder = "NIXPACKS"
buildCommand = "cd backend && pnpm install && pnpm run build"

[deploy]
startCommand = "cd backend && pnpm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = { default = "5000" }
